# Generated by Django 6.0.5 on 2026-05-18 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_disciplina', models.CharField(max_length=20)),
                ('nome_disciplina', models.CharField(max_length=200)),
                ('codigo_turma', models.CharField(default='A1', max_length=10)),
                ('professor', models.CharField(blank=True, max_length=120)),
                ('num_alunos', models.PositiveIntegerField(default=30)),
                ('exige_laboratorio', models.BooleanField(default=False)),
                ('departamento', models.CharField(choices=[('GGE', 'Geografia'), ('GAG', 'Análise Geoambiental'), ('GGO', 'Geologia e Geofísica'), ('PPGEO', 'PG Geografia'), ('PPGDOT', 'PG Din. Oceanos e Terra'), ('EXT', 'Outros / Externo')], default='GGE', max_length=10)),
                ('observacao', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['departamento', 'nome_disciplina', 'codigo_turma'],
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('bloco', models.CharField(choices=[('O', 'Bloco O'), ('P', 'Bloco P')], max_length=1)),
                ('capacidade', models.PositiveIntegerField()),
                ('eh_laboratorio', models.BooleanField(default=False)),
                ('observacao', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['bloco', 'numero'],
                'unique_together': {('numero', 'bloco')},
            },
        ),
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira')])),
                ('hora_inicio', models.CharField(max_length=5)),
                ('hora_fim', models.CharField(max_length=5)),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alocacoes', to='alocacao.sala')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='alocacao.turma')),
            ],
            options={
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
    ]
