# Generated by Django 5.2.14 on 2026-05-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alocacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alocacao',
            options={'ordering': ['dia_semana', 'hora_inicio'], 'verbose_name': 'Alocação', 'verbose_name_plural': 'Alocações'},
        ),
        migrations.AlterField(
            model_name='alocacao',
            name='dia_semana',
            field=models.IntegerField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')]),
        ),
    ]
